### ISSUE TITLE
Could I see the Baseline Model?

### ISSUE THREAD

**Issue by CinKKKyo** [liuning-scu-cn/AmurTigerReID#1]
I am new in re-ID task, it's really takes me a lot of time to do but failed to re-implmentation the Baseline Method, so could u guys do me a favor? I just want to study how to make the data proprecessing and model buliding:），Thanks a lot!

**Comment by liuning-scu-cn** [comment]
you could see https://github.com/layumi/Person_reID_baseline_pytorch, and I hope it will help you well.






------------------ 原始邮件 ------------------
发件人: "CinKKKyo"<notifications@github.com>;
发送时间: 2019年7月31日(星期三) 下午2:41
收件人: "liuning-scu-cn/AmurTigerReID"<AmurTigerReID@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [liuning-scu-cn/AmurTigerReID] Could I see the Baseline Model? (#1)




I am new in re-ID task, it's really takes me a lot of time to do but failed to re-implmentation the Baseline Method, so could u guys do me a favor? I just want to study how to make the data proprecessing and model buliding:），Thanks a lot!

**Comment by CinKKKyo** [comment]
> you could see https://github.com/layumi/Person_reID_baseline_pytorch, and I hope it will help you well.
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "CinKKKyo"<notifications@github.com>; 发送时间: 2019年7月31日(星期三) 下午2:41 收件人: "liuning-scu-cn/AmurTigerReID"<AmurTigerReID@noreply.github.com>; 抄送: "Subscribed"<subscribed@noreply.github.com>; 主题: [liuning-scu-cn/AmurTigerReID] Could I see the Baseline Model? (#1) I am new in re-ID task, it's really takes me a lot of time to do but failed to re-implmentation the Baseline Method, so could u guys do me a favor? I just want to study how to make the data proprecessing and model buliding:），Thanks a lot! — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by CinKKKyo** [comment]
appreciate it! Have a nice day!
